### ISSUE TITLE
No issue tracker for your fork of Your Turn

### ISSUE THREAD

**Issue by MNielson** [EndlessFractal/EndlessFractal#1]
A few months ago you forked [YourTurn](https://github.com/Autmor/yourTurn). 
From what I've seen your version improved quite a bit over the original, sadly, there is no Issue tracker on your fork.
I'm not sure if this is intentional as you seem to be active in the issue tracker of the original project.

So I guess my question is: Why is there no issue tracker for your fork of Your Turn?
You seem to be an active and capable developer and I'd love to see you develop YourTurn further.

**Comment by EndlessFractal** [comment]
It was an oversight, and it should be fixed now!

Apologies!
