### ISSUE TITLE
Semantic highlighting in Sublime Text

### ISSUE THREAD

**Issue by finnlogin** [EndlessFractal/EndlessFractal#2]
Hi there!

Today I checked my email and found your reply. I was on cloud nine when semantic highlighting started working in my VSCodium. Thank you very much!

I checked your profile on Github and found out that you use Sublime Text too. I'm curious if it's possible to activate semantic highlighting similar to VSCode/VSCodium for Python in Sublime Text? Sublime Text has its own charm but I'm a novice programmer, so I need semantic highlighting to learn more effectively.

I would appreciate your help in this matter.

**Comment by EndlessFractal** [comment]
I use Sublime Text very often as a text editor, but if need to code I usually resort to VSCodium.

Some syntax highlighters:
https://packagecontrol.io/packages/Python%20Improved
https://packagecontrol.io/packages/MagicPython
https://packagecontrol.io/packages/Scenic

You can check some language servers here:
https://lsp.sublimetext.io/language_servers/#python

Let me know if any of that worked for you.

**Comment by finnlogin** [comment]
Thank you for the response! Truth be told, VScodium is more than enough for comfortable coding. I was just curious whether Sublime Text could do the same semantic highlighting as VSCodium.
